title: Matthew's Projects
description: Trying to get hired.
show_downloads: true
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
baseurl: "/Matt_1393.github.io"
plugins:
  - jekyll-remote-theme
permalink: pretty
